[package]
name = "kvs"
version = "0.1.0"
authors = ["Chufan Chen <allenplato28@gmail.com>"]
description = "A key-value store"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "0.11.0"
clap = "2.33.3"
predicates = "1.0.0"
